# Generated by Django 2.1.8 on 2019-05-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('管理员联系电话', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('管理员密码', models.CharField(blank=True, max_length=20, null=True)),
                ('管理员姓名', models.CharField(blank=True, max_length=20, null=True)),
                ('管理员工号', models.IntegerField(blank=True, null=True)),
                ('管理员邮箱', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '管理员',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChargeError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('充电行为类型编号', models.IntegerField(blank=True, null=True)),
                ('车牌号', models.CharField(blank=True, max_length=10, null=True)),
                ('信用分值小计', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '充电故障',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('充电行为类型编号', models.IntegerField(primary_key=True, serialize=False)),
                ('充电行为类型', models.CharField(blank=True, max_length=40, null=True)),
                ('行为分值', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '充电行为',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('订单号', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('车牌号', models.CharField(blank=True, max_length=10, null=True)),
                ('充电开始时间', models.CharField(blank=True, max_length=255, null=True)),
                ('充电时长', models.IntegerField(blank=True, null=True)),
                ('电桩编号', models.CharField(blank=True, max_length=6, null=True)),
                ('充电行为类型编号', models.IntegerField(blank=True, null=True)),
                ('订单分值小计', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '订单',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('预约号', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('电桩编号', models.CharField(blank=True, max_length=6, null=True)),
                ('车牌号', models.CharField(blank=True, max_length=10, null=True)),
                ('预约充电开始时间', models.CharField(blank=True, max_length=255, null=True)),
                ('预约充电时长', models.IntegerField(blank=True, null=True)),
                ('预约状态', models.IntegerField(blank=True, null=True)),
                ('预约分值小计', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '预约',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('联系电话', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('用户类型', models.IntegerField(blank=True, null=True)),
                ('集团编号', models.IntegerField(blank=True, null=True)),
                ('集团名', models.CharField(blank=True, max_length=50, null=True)),
                ('用户密码', models.CharField(blank=True, max_length=20, null=True)),
                ('用户姓名', models.CharField(blank=True, max_length=20, null=True)),
                ('账号', models.IntegerField(blank=True, null=True)),
                ('邮箱', models.CharField(blank=True, max_length=50, null=True)),
                ('车牌号', models.CharField(blank=True, max_length=10, null=True)),
                ('信用分值', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '用户',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='subs',
            name='联系电话',
            field=models.ForeignKey(db_column='联系电话', on_delete=django.db.models.deletion.DO_NOTHING, to='Webcar.Users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='联系电话',
            field=models.ForeignKey(blank=True, db_column='联系电话', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Webcar.Users'),
        ),
        migrations.AddField(
            model_name='chargeerror',
            name='联系电话',
            field=models.ForeignKey(db_column='联系电话', on_delete=django.db.models.deletion.DO_NOTHING, to='Webcar.Users'),
        ),
        migrations.AddField(
            model_name='chargeerror',
            name='订单号',
            field=models.ForeignKey(db_column='订单号', on_delete=django.db.models.deletion.DO_NOTHING, to='Webcar.Orders'),
        ),
    ]
