# Generated by Django 2.1.8 on 2019-05-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='用户类型',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='账号',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
