# Generated by Django 2.1.8 on 2019-05-27 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0003_auto_20190527_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='联系电话',
            field=models.OneToOneField(max_length=11, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
