# Generated by Django 2.1.8 on 2019-05-27 12:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0005_auto_20190527_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='联系电话',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='users',
            name='账号',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
