# Generated by Django 2.1.8 on 2019-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0008_auto_20190527_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='联系电话',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
