# Generated by Django 2.1.8 on 2019-05-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0010_auto_20190527_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='联系电话',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
