# Generated by Django 2.1.8 on 2019-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0011_auto_20190527_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='用户密码',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
