# Generated by Django 2.1.8 on 2019-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0012_auto_20190601_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='管理员密码',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
