# Generated by Django 2.1.8 on 2019-06-01 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webcar', '0013_auto_20190601_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='使用者',
            field=models.OneToOneField(default='00000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
