# Generated by Django 2.1.8 on 2019-06-01 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0014_users_使用者'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='使用者',
        ),
        migrations.AlterField(
            model_name='users',
            name='联系电话',
            field=models.OneToOneField(default='00000000000', max_length=11, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
