# Generated by Django 2.1.8 on 2019-06-01 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webcar', '0015_auto_20190601_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='用户',
            field=models.OneToOneField(default='00000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='联系电话',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
