# Generated by Django 2.1.8 on 2019-06-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0016_auto_20190601_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='用户',
            new_name='user',
        ),
    ]
