# Generated by Django 2.1.8 on 2019-06-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0017_auto_20190601_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
