# Generated by Django 2.1.8 on 2019-06-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0021_auto_20190602_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='充电时长',
            new_name='oedertime',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='充电行为类型编号',
            new_name='orderactiontype',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='车牌号',
            new_name='ordercarnumber',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='订单分值小计',
            new_name='ordercredit',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='订单号',
            new_name='ordernumber',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='联系电话',
            new_name='orderphone',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='电桩编号',
            new_name='orderpilenumber',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='充电开始时间',
            new_name='orderstarttime',
        ),
        migrations.AlterField(
            model_name='chargeerror',
            name='订单号',
            field=models.ForeignKey(db_column='订单号', on_delete=django.db.models.deletion.DO_NOTHING, to='Webcar.Orders', to_field='订单号'),
        ),
    ]
