# Generated by Django 2.1.8 on 2019-06-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0022_auto_20190602_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeerror',
            name='订单号',
            field=models.ForeignKey(db_column='订单号', on_delete=django.db.models.deletion.DO_NOTHING, to='Webcar.Orders'),
        ),
    ]
