# Generated by Django 2.1.8 on 2019-06-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0023_auto_20190602_1658'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='administers',
        ),
        migrations.AlterModelTable(
            name='chargeerror',
            table='chargingerrors',
        ),
        migrations.AlterModelTable(
            name='errortype',
            table='chargingactions',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='subs',
            table='subscribes',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
