# Generated by Django 2.1.8 on 2019-06-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webcar', '0024_auto_20190602_1717'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='管理员',
        ),
        migrations.AlterModelTable(
            name='chargeerror',
            table='充电行为',
        ),
        migrations.AlterModelTable(
            name='errortype',
            table='充电故障',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='订单',
        ),
        migrations.AlterModelTable(
            name='subs',
            table='预约',
        ),
        migrations.AlterModelTable(
            name='users',
            table='用户',
        ),
    ]
